name: Lint
on:
  push: null
jobs:
  is-reuse-compliant:
    name: Is REUSE compliant?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fsfe/reuse-action@v2
  rust-code-compiles:
    name: Rust code compiles?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/rust-toolchain
      with:
        toolchain: 1.70.0
        targets: thumbv7em-none-eabihf
    - run: 'cargo check --manifest-path extmod/foundation-rust/Cargo.toml

        '
    - run: sudo apt-get install -y gcc-arm-none-eabi
    - run: "cargo check --manifest-path extmod/foundation-rust/Cargo.toml \\\n            --target thumbv7em-none-eabihf\n"
  is-the-rust-code-formatted:
    name: Is the Rust code formatted?
    needs:
    - rust-code-compiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/rust-toolchain
      with:
        toolchain: 1.70.0
        components: rustfmt
    - run: "cargo fmt --manifest-path extmod/foundation-rust/Cargo.toml \\\n          --all -- --check\n"
  is-the-python-code-formatted:
    name: Is the Python code formatted?
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y pycodestyle
    - run: pycodestyle --statistics --exclude translations ports/stm32/boards/Passport
  is-foundation-header-up-to-date:
    name: Is foundation.h header file up to date?
    needs:
    - rust-code-compiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/rust-toolchain
      with:
        toolchain: 1.70.0
    - run: cargo install cbindgen@^0.24 --locked
    - run: "cbindgen --config extmod/foundation-rust/cbindgen.toml \\\n         --output extmod/foundation-rust/include/foundation.h\
        \ \\\n         --verify \\\n         extmod/foundation-rust/\n"
  rust-tests-pass:
    name: Rust tests pass?
    needs:
    - rust-code-compiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/rust-toolchain
      with:
        toolchain: 1.70.0
        targets: null
    - run: "cargo test --manifest-path extmod/foundation-rust/Cargo.toml \\\n           --features std\n"
